ci: update standalone build

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -152,11 +152,75 @@ jobs:
         with:
           path: ./out
 
+  build-standalone:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
+
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with:
+          node-version: "18.20.6"
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+
+      - name: Restore cache
+        uses: actions/cache@v4
+        with:
+          path: |
+            .next/cache
+          # Generate a new cache whenever packages or source files change.
+          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+          # If source files changed but packages didn't, rebuild from a prior cache.
+          restore-keys: |
+            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
+
+      - name: Install dependencies
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+
+      - name: Update env with secrets
+        run: |
+          touch .env.production
+          echo "# environment config" > .env.production
+          echo MONGO_URL=${{ secrets.MONGO_URL }} >> .env.production
+          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env.production
+
+      - name: Build with Next.js
+        env:
+          BUILD_TYPE: standalone
+        run: |
+          echo "Building for $BUILD_TYPE"
+          ${{ steps.detect-package-manager.outputs.runner }} next build && tsc --project tsconfig.standalone.json
+
+      - name: Upload build artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: build-standalone-artifacts
+          path: ./
+
   # Deployment job cygnus hosting cpanel node application
   deploy-cyngus-hosting:
     runs-on: ubuntu-latest
     environment: production
-    needs: build
+    needs: build-standalone
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -164,7 +228,7 @@ jobs:
       - name: Download build artifacts
         uses: actions/download-artifact@v4
         with:
-          name: build-artifacts
+          name: build-standalone-artifacts
           path: |
             ./_next
             ./node_modules
